-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
--vim.keymap.set("n", "<leader><leader>", function ()
--  local builtin = require("telescope.builtin")
--  builtin.find_files({
--    hidden = true,
--    no_ignore = true,
--  })
--end, { desc = "Find files"})
